# -*- coding: utf-8 -*-
"""Employee Analytics System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14slsaWp0_LQjxPdvCzISzIWWP-YvTaIB
"""

#Employee Analytics System

"""
Employee Analytics System

Features:
1. Average Salary
2. Highest Paid Employee
3. Lowest Paid Employee
4. Salary Filtering
5. Department-wise Employee Count
6. Average Experience
7. Employee Grading
8. Average Salary by Department

Author: Param Mangukiya
"""

import pandas as pd
import numpy as np

data = {
    "Employee_ID": [1,2,3,4,5],
    "Name": ["Rahul","Amit","Riya","Priya","Karan"],
    "Department": ["IT","HR","IT","Finance","HR"],
    "Salary": [40000,35000,45000,60000,38000],
    "Experience": [1,3,4,6,2]
}

df = pd.DataFrame(data)

print("\n=== 1. Average Salary ===")
print(df["Salary"].mean())

print("\n=== 2. Highest Paid Employee ===")
print(df[df["Salary"] == df["Salary"].max()]["Name"])

print("\n=== 3. Lowest Paid Employee ===")
print(df[df["Salary"] == df["Salary"].min()]["Name"])

print("\n=== 4. Employees with Salary > 40000 ===")
print(df[df["Salary"]>40000])

print("\n=== 5. Department-wise Employee Count ===")
print(df["Department"].value_counts())

print("\n=== 6. Average Experience ===")
print(df["Experience"].mean())

print("\n=== 7. Bonus ===")
conditions = [
    df['Salary'] >= 50000,
    df['Salary'] >= 40000,
    df['Salary'] < 40000
]
choices = ['A', 'B', 'C']
df['Grade'] = np.select(conditions, choices, default='C')
print(df)



print("\n=== 8. Average Salary By Department ===")
print(df.groupby("Department")["Salary"].mean())