# -*- coding: utf-8 -*-
"""Student Management System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oz_tWELzHvkTo5YzMEP-OLG34CRDmpTM
"""

"""
Student Management System

Features:
1. Add Student
2. View Students
3. Average Marks
4. Highest Marks
5. Lowest Marks
6. Students Above 85
7. Students From Surat
8. Grade Report
9. Sort By Marks
10. Show Missing Values
11. Delete Student
12. Update Marks
13. Save Data to CSV
14. Load Data from CSV

Author: Param Mangukiya
"""



import pandas as pd

# ==============================
# Load Existing Data
# ==============================

try:
    df = pd.read_csv("students.csv")
    print("Data Loaded Successfully")
except FileNotFoundError:
    df = pd.DataFrame(
        columns=["Name", "Age", "Marks", "City"]
    )
    print("New Database Created")


def update_grade():
    global df

    if len(df) > 0:
        df["Grade"] = df["Marks"].apply(
            lambda x: "A" if x >= 90 else
                      "B" if x >= 80 else
                      "C"
        )


update_grade()

# ==============================
# Functions
# ==============================

def add_students():
    global df

    name = input("Enter Name: ")
    age = int(input("Enter Age: "))
    marks = int(input("Enter Marks: "))
    city = input("Enter City: ")

    new_row = {
        "Name": name,
        "Age": age,
        "Marks": marks,
        "City": city
    }

    df.loc[len(df)] = new_row

    update_grade()

    print("Student Added Successfully")


def view_student():
    print("\n==== STUDENT DETAILS ====")
    print(df)


def average_marks():
    print("\n==== Average Marks ====")
    print(df["Marks"].mean())


def highest_marks():
    print("\n==== Highest Marks ====")
    print(df["Marks"].max())


def lowest_marks():
    print("\n==== Lowest Marks ====")
    print(df["Marks"].min())


def marks_above_85():
    print("\n==== Students Above 85 ====")
    print(df[df["Marks"] > 85])


def students_from_surat():
    print("\n==== Students From Surat ====")
    print(df[df["City"] == "Surat"])


def grade_report():
    print("\n==== Grade Report ====")
    print(df.groupby("Grade")["Name"].count())


def sort_by_marks():
    print("\n==== Sorted By Marks ====")
    print(df.sort_values(by="Marks", ascending=False))


def show_missing_values():
    print("\n==== Missing Values ====")
    print(df.isnull().sum())


def delete_student():
    global df

    name = input("Enter Student Name To Delete: ")

    df = df[df["Name"] != name]

    update_grade()

    print("Student Deleted Successfully")


def update_marks():
    global df

    name = input("Enter Student Name: ")
    marks = int(input("Enter New Marks: "))

    df.loc[df["Name"] == name, "Marks"] = marks

    update_grade()

    print("Marks Updated Successfully")


def save_data():
    df.to_csv("students.csv", index=False)
    print("Data Saved Successfully")


# ==============================
# Main Menu
# ==============================

while True:

    print("\n====== MENU ======")
    print("1. Add Student")
    print("2. View Students")
    print("3. Average Marks")
    print("4. Highest Marks")
    print("5. Lowest Marks")
    print("6. Students Above 85")
    print("7. Students From Surat")
    print("8. Grade Report")
    print("9. Sort By Marks")
    print("10. Show Missing Values")
    print("11. Delete Student")
    print("12. Update Marks")
    print("13. Save Data")
    print("14. Exit")

    try:
        choice = int(input("Enter Your Choice: "))
    except ValueError:
        print("Invalid Input")
        continue

    if choice == 1:
        add_students()

    elif choice == 2:
        view_student()

    elif choice == 3:
        average_marks()

    elif choice == 4:
        highest_marks()

    elif choice == 5:
        lowest_marks()

    elif choice == 6:
        marks_above_85()

    elif choice == 7:
        students_from_surat()

    elif choice == 8:
        grade_report()

    elif choice == 9:
        sort_by_marks()

    elif choice == 10:
        show_missing_values()

    elif choice == 11:
        delete_student()

    elif choice == 12:
        update_marks()

    elif choice == 13:
        save_data()

    elif choice == 14:
        print("Program Ended Successfully")
        break

    else:
        print("Invalid Choice")